vulnerabilities:
  - id: CVE-2025-7783
    statement: "https://en.wiki.bluespice.com/wiki/Security:Security_Advisories"
  - id: CVE-2026-59873
    statement: "https://en.wiki.bluespice.com/wiki/Security:Security_Advisories"

